config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    // $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    $builder->connect('/', ['controller' => 'Articles', 'action' => 'index']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */

    $builder->connect('/article/{slug}', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
    $builder->connect('/page/{slug}', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);

    $builder->connect('/now', ['controller' => 'Articles', 'action' => 'now']);
    $builder->connect('/micro', ['controller' => 'Articles', 'action' => 'micro']);

    $builder->scope("/articles", function (RouteBuilder $builder) {
        $builder->connect('/tagged/*', ['controller' => 'Articles', 'action' => 'tags']);
        $builder->connect('/v/{slug}', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
    });

    $builder->prefix('Admin', function (RouteBuilder $builder) {
        $builder->fallbacks();
    });

    // api
    $builder->prefix('Api', function (RouteBuilder $builder) {
        $builder->setExtensions(['json']);

        $builder->prefix('version1', ['path' => '/v1'], function (RouteBuilder $builder) {
            $builder->setExtensions(['json']);
            $builder->connect('/{controller}/{action}/*');
        });
    });

    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *     
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/ArticleType.php
<?php
declare(strict_types=1);

namespace MeowBlog\Model\Entity;

enum ArticleType: string
{
    case Article = 'meowblog/articles.type.article';
    case Page = 'meowblog/articles.type.page';
    case Micro = 'meowblog/articles.type.micro';

    /**
     * Return list of cases that is uuitable for use with Html Selects
     *
     * @return array
     */
    public static function list(): array
    {
        $list = [];
        foreach (self::cases() as $case) {
            $list[$case->value] = $case->name;
        }

        return $list;
    }
}

src/Model/Table/ArticlesTagsTable.php
<?php
declare(strict_types=1);

namespace MeowBlog\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * ArticlesTags Model
 *
 * @property \MeowBlog\Model\Table\ArticlesTable&\Cake\ORM\Association\BelongsTo $Articles
 * @property \MeowBlog\Model\Table\TagsTable&\Cake\ORM\Association\BelongsTo $Tags
 * @method \MeowBlog\Model\Entity\ArticlesTag newEmptyEntity()
 * @method \MeowBlog\Model\Entity\ArticlesTag newEntity(array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[] newEntities(array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag get($primaryKey, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\ArticlesTag[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class ArticlesTagsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('articles_tags');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Articles', [
            'foreignKey' => 'article_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Tags', [
            'foreignKey' => 'tag_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('article_id')
            ->requirePresence('article_id', 'create')
            ->notEmptyString('article_id');

        $validator
            ->integer('tag_id')
            ->requirePresence('tag_id', 'create')
            ->notEmptyString('tag_id');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn('article_id', 'Articles'), ['errorField' => 'article_id']);
        $rules->add($rules->existsIn('tag_id', 'Tags'), ['errorField' => 'tag_id']);

        return $rules;
    }
}

src/Model/Table/LinksTable.php
<?php
declare(strict_types=1);

namespace MeowBlog\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Links Model
 *
 * @property \MeowBlog\Model\Table\BlogsTable&\Cake\ORM\Association\BelongsTo $Blogs
 *
 * @method \MeowBlog\Model\Entity\Link newEmptyEntity()
 * @method \MeowBlog\Model\Entity\Link newEntity(array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\Link[] newEntities(array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\Link get($primaryKey, $options = [])
 * @method \MeowBlog\Model\Entity\Link findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \MeowBlog\Model\Entity\Link patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\Link[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \MeowBlog\Model\Entity\Link|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \MeowBlog\Model\Entity\Link saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \MeowBlog\Model\Entity\Link[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\Link[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\Link[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \MeowBlog\Model\Entity\Link[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class LinksTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('links');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->belongsTo('Blogs', [
            'foreignKey' => 'blog_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('blog_id')
            ->notEmptyString('blog_id');

        $validator
            ->scalar('title')
            ->maxLength('title', 255)
            ->requirePresence('title', 'create')
            ->notEmptyString('title');

        $validator
            ->scalar('url')
            ->maxLength('url', 255)
            ->requirePresence('url', 'create')
            ->notEmptyString('url');

        $validator
            ->integer('weight')
            ->notEmptyString('weight');

        $validator
            ->boolean('external')
            ->notEmptyString('external');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn('blog_id', 'Blogs'), ['errorField' => 'blog_id']);

        return $rules;
    }
}

src/Controller/Admin/ArticlesController.php
<?php
declare(strict_types=1);

namespace MeowBlog\Controller\Admin;

use Authorization\Exception\ForbiddenException;
use MeowBlog\Controller\AppController;
use MeowBlog\Job\UpdateAiSummaryJob;
use MeowBlog\Model\Entity\ArticleType;
use MeowBlog\Services\ArticlesManagerServiceInterface;
use MeowBlog\Services\OpenaiChatServiceInterface;
use Symfony\Component\VarDumper\Cloner\Data;

/**
 * Articles Controller
 *
 * @property \MeowBlog\Model\Table\ArticlesTable $Articles
 * @method \MeowBlog\Model\Entity\Article[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ArticlesController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->Authorization->skipAuthorization();

        $this->paginate = [
            //'contain' => ['Users', 'Blogs'],
        ];
        $articles = $this->paginate($this->Articles->find('all', [
            'contain' => ['Users', 'Blogs'],
        ]));

        $this->set(compact('articles'));
    }

    /**
     * View method
     *
     * @param string|null $id Article id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $article = $this->Articles->get($id, contain: ['Users', 'Tags', 'Blogs']);

        $this->Authorization->skipAuthorization();

        $this->set(compact('article'));
    }

    /**
     * Add method
     *
     * @param \MeowBlog\Services\ArticlesManagerServiceInterface $articlesManager articlesManager
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add(ArticlesManagerServiceInterface $articlesManager)
    {
        $article = $this->Articles->newEmptyEntity();
        try {
            $this->Authorization->authorize($article);
        } catch (ForbiddenException $e) {
            $this->Flash->error(__('You are not allowed to create articles.'));

            return $this->redirect($this->referer());
        }

        if ($this->request->is('post')) {
            if ($articlesManager->saveToDatabase($article, $this->request)) {
                $this->Flash->success(__('The article has been saved.'));

                $data = [
                    'article_id' => $article->id,
                    'original_text' => $article->body,
                ];

                $this->Queue->push(UpdateAiSummaryJob::class, data: $data);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The article could not be saved. Please, try again.'));
        }

        $articleTypes = ArticleType::list();


        // $users = $this->Articles->Users->find('list', ['limit' => 200])->all();
        // $tags = $this->Articles->Tags->find('list', ['limit' => 200])->all();
        $blogs = $this->Articles->Blogs->find('list', ['limit' => 200])->all();
        $this->set(compact('blogs', 'article', 'articleTypes'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Article id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $article = $this->Articles->get($id, contain: ['Tags']);

        try {
            $this->Authorization->authorize($article);
        } catch (ForbiddenException $e) {
            $this->Flash->error(__('You are not allowed to edit this article.'));

            return $this->redirect($this->referer());
        }

        if ($this->request->is(['patch', 'post', 'put'])) {
            $article = $this->Articles->patchEntity($article, $this->request->getData());
            if ($this->Articles->save($article)) {
                $this->Flash->success(__('The article has been saved.'));

                $data = [
                    'article_id' => $article->id,
                    'original_text' => $article->body,
                ];

                $this->Queue->push(UpdateAiSummaryJob::class, data: $data);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The article could not be saved. Please, try again.'));
        }

        $articleTypes = ArticleType::list();

        // $users = $this->Articles->Users->find('list', ['limit' => 200])->all();
        // $tags = $this->Articles->Tags->find('list', ['limit' => 200])->all();
        $blogs = $this->Articles->Blogs->find('list', ['limit' => 200])->all();
        $this->set(compact('blogs', 'article', 'articleTypes'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Article id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $article = $this->Articles->get($id);

        try {
            $this->Authorization->authorize($article);
        } catch (ForbiddenException $e) {
            $this->Flash->error(__('You are not allowed to delete this article.'));

            return $this->redirect($this->referer());
        }

        if ($this->Articles->delete($article)) {
            $this->Flash->success(__('The article has been deleted.'));
        } else {
            $this->Flash->error(__('The article could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function summarize(OpenaiChatServiceInterface $ai, $id = null)
    {
        $this->Authorization->skipAuthorization();

        $article = $this->Articles->get($id);

        $result = $ai->getTextSummary($article->body);

        $article->summary = $result;
        $this->Articles->save($article);
    }
}

templates/Articles/add.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var \MeowBlog\Model\Entity\Article $article
 * @var \Cake\Collection\CollectionInterface|string[] $users
 * @var \Cake\Collection\CollectionInterface|string[] $tags
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('List Articles'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="articles form content">
            <?= $this->Form->create($article) ?>
            <fieldset>
                <legend><?= __('Add Article') ?></legend>
                <?php
                    // echo $this->Form->control('user_id', ['options' => $users]);
                    echo $this->Form->control('title');
                    // echo $this->Form->control('slug');
                    echo $this->Form->control('body');
                    echo $this->Form->control('published');
                    //echo $this->Form->control('tags._ids', ['options' => $tags]);
                    echo $this->Form->control('tag_string', ['type' => 'text']);
                ?>
            </fieldset>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Articles/edit.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var \MeowBlog\Model\Entity\Article $article
 * @var string[]|\Cake\Collection\CollectionInterface $users
 * @var string[]|\Cake\Collection\CollectionInterface $tags
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $article->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $article->id), 'class' => 'side-nav-item']
            ) ?>
            <?= $this->Html->link(__('List Articles'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="articles form content">
            <?= $this->Form->create($article) ?>
            <fieldset>
                <legend><?= __('Edit Article') ?></legend>
                <?php
                    echo $this->Form->control('user_id', ['options' => $users]);
                    echo $this->Form->control('title');
                    echo $this->Form->control('slug');
                    echo $this->Form->control('body');
                    echo $this->Form->control('published');
                    // echo $this->Form->control('tags._ids', ['options' => $tags]);
                    echo $this->Form->control('tag_string', ['type' => 'text']);
                ?>
            </fieldset>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Articles/index.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var \Meowblog\Model\Entity\Article[] $articles
 * @var bool $currentBlog
 */
?>
<div class="articles index content">

    <?= $homePage ? $this->Markdown->parse($homePage) : '' ?>

    <h3><?= __('Latest Articles') ?></h3>
    <div style="margin-bottom: 1em;">
    <?php foreach ($articles as $article): ?>
        <div>
            <a href="<?= !$this->Articles->isInCurrentBlog($article) ? 'https://'. $article->blog->domain : '' ?><?= $this->Url->build([
                'controller' => 'Articles',
                'action' => 'view',
                $article->slug
            ]) ?>" class="contrast"><?= $article->title ?></a>
            <small>
                <?php if (!$this->Articles->isInCurrentBlog($article)) : ?>
                    <?= __('in') ?>
                    <?= $this->Html->link($article->blog->title, 'https://' . $article->blog->domain) ?>
                <?php endif; ?>
            </small>
        </div>
    <?php endforeach; ?>
    </div>
    <div class="paginator">
        <nav>
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?php //$this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        </nav>
        <p>
            <small><?= $this->Paginator->counter(__('This blog has {{count}} article(s) total')) ?></small>
        </p>
    </div>
</div>

templates/Articles/micro.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var array<\MeowBlog\Model\View\ArticleViewModel> $articles
 */
?>
<div class="articles index content">

    <h3><?= __('Microblog') ?></h3>
    <div style="margin-bottom: 1em;">
    <?php foreach ($articles as $article): ?>
        <div class="micro-post">
            <div style="margin-bottom: 8px;">
            <mark data-tooltip="<?= $article->getArticle()->created ?>"><?= $this->Time->timeAgoInWords($article->getArticle()->created) ?></mark>
            </div>
            <?= $this->Markdown->parse($article->getArticle()->body)?>
            <!--<small><a class="contrast" href="#">Conversation</a></small>-->
        </div>
    <?php endforeach; ?>
    </div>
    <div class="paginator">
        <nav>
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?php //$this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        </nav>
        <p>
            <small><?= $this->Paginator->counter(__('This blog has {{count}} article(s) total')) ?></small>
        </p>
    </div>
</div>

templates/Articles/now.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var ?\MeowBlog\Model\Entity\Article $content
 */
?>
<div class="headings">
    <h2><?= __('Now') ?></h2>
    <h3><?= $content ? __('Last updated {0}', $content->created ) : '' ?></h3>
</div>
<div id="article">
    <p><?= __('This is my {0} page, a summary of what im currently doing or enjoying.', $this->Html->link('/now', 'https://nownownow.com/about', ['target' => '_blank']))?></p>
    <div>
        <?php if (!$content) : ?>
            <p><?= __('There is no update, come back later.') ?></p>
        <?php else : ?>
            <?= $this->Markdown->parse($content->body); ?>
        <?php endif; ?>
    </div>
</div>

templates/Articles/stats.php
<div class="article">
<!-- !!TODO Rename this documment and controller's function -->
<h1>Graph</h1>

<div class="epg" style=" margin: 20px 0;">
<div class="epg__year">2023</div>
                <div class="epg__months">
                    <div>Jan</div>
                    <div>Feb</div>
                    <div>Mar</div>
                    <div>Apr</div>
                    <div>May</div>
                    <div>Jun</div>
                    <div>Jul</div>
                    <div>Aug</div>
                    <div>Sep</div>
                    <div>Oct</div>
                    <div>Nov</div>
                    <div>Dec</div>
                </div>
    <div class="epg__squares">
<?php
if ($offset) {
    foreach (range(1, $offset) as $_) {
        echo '<div class="epg__box epg__box--empty"></div>';
    }
}

foreach(range(0, $daysCount -1) as $i) {
    if (array_search($i, $daysWithArticle) !== false) {
        echo '<div class="epg__box epg__hasPost"></div>';
    } else {
        echo '<div class="epg__box"></div>';
    }
}
?>
</div></div>

Based on https://postgraph.rknight.me/

</div>

templates/Articles/tags.php
<!-- In templates/Articles/tags.php -->
<h1>
    Articles tagged with
    <?= $this->Text->toList(h($tags), 'or') ?>
</h1>

<section>
<?php foreach ($articles as $article): ?>
    <article>
        <!-- Use the HtmlHelper to create a link -->
        <h4><?= $this->Html->link(
            $article->title,
            ['controller' => 'Articles', 'action' => 'view', $article->slug]
        ); ?></h4>
        <span><?= h($article->created) ?></span>
        <span>
            &sharp;<?= $article->tag_string ?>
            <?php if ($this->Articles->isInCurrentBlog($article)): ?>
                in  <?= $this->Html->link(
                    $article->blog->title,
                    'https://' . $article->blog->domain
                ); ?>
            <?php endif; ?>
        </span>
    </article>
<?php endforeach; ?>
</section>

templates/Articles/view.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var \MeowBlog\Model\Entity\Article $article
 */
?>

<div class="article">

    <div class="headings">
        <h2><?= $article->title ?></h2>
        <h3>at <?= $article->created ?></h3>
    </div>
    <?php if ($article->summary) : ?>
        <details>
            <summary>🤖 <?= __('AI Summary')?></summary>
            <?= $this->Html->tag('div', $article->summary) ?>
        </details>
    <?php endif; ?>

    <div id="article">
            <?= $this->Markdown->parse($article->body); ?>
        </div>
        <?php if ($article->tags) : ?>
            <div class="tags">
                <nav>
                    <ul>
                        <?php foreach ($article->tags as $tag) : ?>
                            <li><?= $this->Html->link($tag->title, ['controller' => 'Articles', 'action' => 'tags', $tag->title], ['role' => 'button']) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </nav>
            </div>
        <?php endif; ?>
    </div>

</div>

templates/Articles/view_page.php
<?php
/**
 * @var \MeowBlog\View\AppView $this
 * @var \MeowBlog\Model\Entity\Article $article
 */
?>
<div class="headings">
    <h2><?= $article->title ?></h2>
    <h3></h3>
</div>
<div id="article">
    <div>
        <?= $this->Markdown->parse($article->body); ?>
    </div>
</div>